In [2]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
cap = cv.VideoCapture('../content/corgi_race.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    frame = cv.resize(frame, (640, 480))
    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

Can't receive frame (stream end?). Exiting ...


In [3]:
cap = cv.VideoCapture('../content/corgi_race.mp4')
BW_frames = []

while cap.isOpened():
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    frame = cv.resize(frame, (640, 480))
    frame = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    BW_frames.append(frame)
    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

BW_frames = np.array(BW_frames)

Can't receive frame (stream end?). Exiting ...


In [4]:
def correlation_with_stride(image, m, n, stride, filter_matrix):
  height, width = image.shape
  filter_height = m
  filter_width = n
  result_height = (height - filter_height) // stride + 1
  result_width = (width - filter_width) // stride + 1
  result = np.empty((result_height, result_width), dtype=float)

  channel_data = image
  for i in range(0, result_height):
    for j in range(0, result_width):
      submatrix = channel_data[i*stride:i*stride+filter_height, j*stride:j*stride+filter_width]
      correlation = np.abs(np.sum(submatrix * filter_matrix))
      result[i][j] = correlation

  return result

In [18]:
print(BW_frames[0])

[[ 62  82  87 ... 117 115  75]
 [ 62  82  87 ... 116 113  73]
 [ 62  83  88 ... 112 110  70]
 ...
 [ 59  76  76 ...  80  83  63]
 [ 59  76  75 ...  78  82  62]
 [ 59  76  77 ...  77  82  62]]


In [5]:
#Filtro de média 3x3
filter_height = 3
filter_width = 3
filter_matrix = np.array([[1/9,1/9,1/9],
                          [1/9,1/9,1/9],
                          [1/9,1/9,1/9]])

In [6]:
filtered_frames = []

for f in BW_frames:
    filtered_frames.append(correlation_with_stride(f, filter_height, filter_width, 1, filter_matrix).astype('uint8'))

filtered_frames = np.array(filtered_frames)

In [7]:
for f in filtered_frames:
    cv.imshow('frame', f)
    if cv.waitKey(1) == ord('q'):
        break
    cv.destroyAllWindows()

: 

In [ ]:
ddepth = -1

ind = 0
kernel_size = 3 + 2 * (ind % 5)
kernel = np.ones((kernel_size, kernel_size), dtype=np.float32)
kernel /= (kernel_size * kernel_size)

filtered_frames_cv = []

vid_3_channels = cv.merge(BW_frames, BW_frames, BW_frames)

for f in vid_3_channels:
    filtered_frames_cv.append(cv.filter2D(f, ddepth, kernel))

filtered_frames_cv = np.array(filtered_frames_cv)

In [ ]:
for f in filtered_frames_cv:
    cv.imshow('frame', f)
    if cv.waitKey(1) == ord('q'):
        break
    cv.destroyAllWindows()

In [ ]:
laplacian_frames = []

filter_matrix = np.array([[-1, -1, -1],
                          [-1, 8, -1],
                          [-1, -1, -1]])

for f in BW_frames:
    laplacian_frames.append(correlation_with_stride(f, filter_height, filter_width, 1, filter_matrix).astype('uint8'))

laplacian_frames = np.array(filtered_frames)

In [ ]:
for f in laplacian_frames:
    cv.imshow('frame', f)
    if cv.waitKey(1) == ord('q'):
        break
    cv.destroyAllWindows()

In [ ]:
laplacian_frames_cv = []

filter_matrix = np.array([[-1, -1, -1],
                          [-1, 8, -1],
                          [-1, -1, -1]])

for f in vid_3_channels:
    laplacian_frames_cv.append(correlation_with_stride(f, filter_height, filter_width, 1, filter_matrix).astype('uint8'))

laplacian_frames_cv = np.array(filtered_frames)

In [ ]:
for f in laplacian_frames_cv:
    cv.imshow('frame', f)
    if cv.waitKey(1) == ord('q'):
        break
    cv.destroyAllWindows()

In [ ]:
sobel_x_frames = []

filter_matrix = np.array([[-1, -2, -1],
                          [0, 0, 0],
                          [1, 2, 1]])

for f in BW_frames:
    sobel_x_frames.append(correlation_with_stride(f, filter_height, filter_width, 1, filter_matrix).astype('uint8'))

sobel_x_frames = np.array(filtered_frames)


sobel_y_frames = []

filter_matriy = np.array([[-1, 0, 1],
                          [-2, 0, 2],
                          [-1, 0, 1]])

for f in BW_frames:
    sobel_y_frames.append(correlation_with_stride(f, filter_height, filter_width, 1, filter_matriy).astype('uint8'))

sobel_y_frames = np.array(filtered_frames)

sobel_frames = np.add(sobel_x_frames, sobel_y_frames)

In [ ]:
sobel_x_frames_cv = []
sobel_y_frames_cv = []

for f in vid_3_channels:
    sobel_x_frames_cv.append(cv.Sobel(f, 1, 0, ddepth=-1, ksize=3))

for f in vid_3_channels:
    sobel_x_frames_cv.append(cv.Sobel(f, 0, 1, ddepth=-1, ksize=3))

sobel_frames_cv = np.add(sobel_x_frames_cv, sobel_y_frames_cv)

In [ ]:
for f in sobel_frames_cv:
    cv.imshow('frame', f)
    if cv.waitKey(1) == ord('q'):
        break
    cv.destroyAllWindows()